extends:
  - 'plugin:@angular-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - '@angular-eslint/eslint-plugin'
  - 'eslint-plugin-import'
  - 'prettier'
ignorePatterns:
  - '*.html'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
  '@angular-eslint/prefer-standalone': 'off'
  '@typescript-eslint/no-wrapper-object-types': 'off'
  '@typescript-eslint/no-non-null-assertion': 'warn'
  '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn'
  '@angular-eslint/component-class-suffix': error
  '@angular-eslint/directive-class-suffix': error
  '@angular-eslint/no-input-rename': error
  '@angular-eslint/no-output-on-prefix': error
  '@angular-eslint/no-output-rename': error
  '@angular-eslint/use-pipe-transform-interface': error
  '@typescript-eslint/no-unused-vars': ['warn', { 'ignoreRestSiblings': true }]
  '@typescript-eslint/consistent-type-definitions': error
  '@typescript-eslint/dot-notation': 'off'
  '@typescript-eslint/explicit-member-accessibility':
    - 'off'
    - accessibility: explicit
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - 'static-field'
        - 'instance-field'
        - 'static-method'
        - 'instance-method'
  '@typescript-eslint/naming-convention':
    - error
    - selector: variable
      format:
        - camelCase
        - UPPER_CASE
      leadingUnderscore: forbid
      trailingUnderscore: forbid
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/no-empty-interface': error
  '@typescript-eslint/no-inferrable-types':
    - error
    - ignoreParameters: true
  '@typescript-eslint/no-misused-new': error
  '@typescript-eslint/no-shadow':
    - error
    - hoist: all
  '@typescript-eslint/no-unused-expressions': error
  '@typescript-eslint/prefer-function-type': error
  '@typescript-eslint/unified-signatures': error
  'prettier/prettier': 'off'
  constructor-super: error
  curly: error
  dot-notation: 'off'
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  id-denylist: 'off'
  id-match: 'off'
  import/no-deprecated: warn
  max-len:
    - error
    - code: 270
  no-bitwise: error
  no-caller: error
  no-console:
    - error
    - allow:
        - log
        - warn
        - dir
        - timeLog
        - assert
        - clear
        - count
        - countReset
        - group
        - groupEnd
        - table
        - dirxml
        - error
        - groupCollapsed
        - Console
        - profile
        - profileEnd
        - timeStamp
        - context
  no-debugger: error
  no-empty: 'off'
  no-empty-function: 'off'
  no-eval: error
  no-fallthrough: error
  no-new-wrappers: error
  no-restricted-imports:
    - error
    - rxjs/Rx
  no-shadow: 'off'
  no-throw-literal: error
  no-undef-init: error
  no-underscore-dangle: 'off'
  no-unused-expressions: 'off'
  no-unused-labels: error
  no-var: error
  prefer-const: error
  radix: error
  spaced-comment:
    - error
    - always
    - exceptions:
        - '*'
        - '-'
